#!/usr/bin/env bash 

NAME=$1
MINIMUM=$2
MAXIMUM=$3
PROCESS_FILE="/tmp/.fido-$NAME"

while read VALUE 
do

  if [ -f $PROCESS_FILE ]; then

    echo $VALUE > $PROCESS_FILE 
  
    if (( $VALUE > $MAXIMUM )); then 
      echo "$NAME has detected a value of $VALUE which is more than your maximum of $MAXIMUM"
      rm $PROCESS_FILE
    fi

    if (( $VALUE < $MINIMUM )); then
      echo "$NAME has detected a value of $VALUE which is less your maximum of $MINIMUM"
      rm $PROCESS_FILE
    fi

  else 
    # Do nothing unless the VALUE is back in bounds, in which case blank the file
    if (( $VALUE < $MAXIMUM )) && (( $VALUE > $MINIMUM )); then 
      echo "$NAME is now in bounds with a value of $VALUE"
      touch $PROCESS_FILE
      echo $VALUE > $PROCESS_FILE 
    fi
  fi
done < /dev/stdin
