#!/usr/bin/env node

var exec = require('child_process').exec;
console.log('Installing...')
var child = exec('cd ' + __dirname + '; sudo npm install;')
child.stdout.on('data', function(data) {
  console.log(data)
})
child.stderr.on('data', function(data) {
  console.log(data)
})
child.on('close', function(code) {
  var child2 = exec('sudo apt-get install mailutils -y')
  child.stdout.on('data', function(data) {
    console.log(data)
  })
  child.stderr.on('data', function(data) {
    console.log(data)
  })
  child.on('close', function(code) {
    console.log('Installing mailutils finished with code ' + code)
  })
})
