#!/usr/bin/env node

var exec = require('child_process').exec;
console.log('Installing...')
var child = exec('cd ' + __dirname + '; sudo npm install;')
child.stdout.on('data', function(data) {
  console.log(data)
})
child.stderr.on('data', function(data) {
  console.log(data)
})
child.on('close', function(code) {
  var child2 = exec('sudo apt-get update')
  child2.stdout.on('data', function(data) {
    console.log(data)
  })
  child2.stderr.on('data', function(data) {
    console.log(data)
  })
  child2.on('close', function(code) {
    console.log('Updated apt-get with code ' + code)
    var child3 = exec('sudo apt-get install mailutils -y')
    child3.stdout.on('data', function(data) {
      console.log(data)
    })
    child3.stderr.on('data', function(data) {
      console.log(data)
    })
    child3.on('close', function(code) {
      console.log('Installing postfix finished with code ' + code)
      var child4 = exec('sudo DEBIAN_FRONTEND=noninteractive apt-get install postfix -y')
      child4.stdout.on('data', function(data) {
        console.log(data)
      })
      child4.stderr.on('data', function(data) {
        console.log(data)
      })
      child4.on('close', function(code) {
        console.log('Installing postfix finished with code ' + code)
      })
    })

  })
})
